# Generated by Django 5.1.4 on 2025-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatayu', '0002_signup_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='claims/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
